services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-server:latest
    container_name: node-container
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./certs:/app/certs
      - ./logs:/app/logs
      - ./src/handlers:/app/src/handlers
    depends_on:
      - mongo
    entrypoint:
      ["/app/wait-for-it.sh", "mongo:27017", "--", "npm", "run", "start:server"]
    environment:
      - MONGO_URI=mongodb://mongo:27017/appdb
      - CHOKIDAR_USEPOLLING=true # Opcjonalne dla lepszej obsługi
      - CHOKIDAR_INTERVAL=100 # Krótszy czas sprawdzania zmian
      - NODE_OPTIONS=--trace-warnings # Opcjonalne do debugowania

  mongo:
    image: mongo:6
    container_name: mongo-container
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db # Mapowanie folderu na hoście
    environment:
      - MONGO_INITDB_DATABASE=appdb

volumes:
  mongo_data:
    external: false # Umożliwia używanie lokalnego folderu, a nie tylko wewnętrznego wolumenu
