services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-server:latest
    container_name: node-container
    networks:
      - my-network
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./certs:/app/certs
      - ./dist:/app/dist
      - ./logs:/app/logs
      - ./src/server/handlers:/app/src/server/handlers
      - ./src/client/locales:/app/src/client/locales
    depends_on:
      - mongo
    entrypoint:
      ["/app/wait-for-it.sh", "mongo", "--", "npm", "run", "start:server"]
    environment:
      - MONGO_URI=mongodb://mongo:27017/appdb
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - NODE_OPTIONS=--trace-warnings

  mongo:
    image: mongo:latest
    container_name: mongo-container
    restart: unless-stopped
    networks:
      - my-network
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=appdb

volumes:
  mongo_data:
    external: false

networks:
  my-network:
    driver: bridge
